# Generated by Django 3.0.5 on 2020-08-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='date',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
