# Generated by Django 3.0.5 on 2020-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('owner', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='null', max_length=30)),
                ('email', models.CharField(default='null', max_length=30)),
                ('number', models.CharField(default='null', max_length=30)),
                ('add', models.CharField(default='null', max_length=30)),
                ('city', models.CharField(default='null', max_length=30)),
                ('state', models.CharField(default='null', max_length=30)),
                ('about', models.CharField(default='null', max_length=100)),
                ('date', models.CharField(default='null', max_length=15)),
                ('photo1', models.ImageField(upload_to='interior/images')),
                ('photo2', models.ImageField(upload_to='interior/images')),
                ('photo3', models.ImageField(upload_to='interior/images')),
                ('photo4', models.ImageField(upload_to='interior/images')),
                ('video', models.FileField(upload_to='interior/video')),
            ],
        ),
    ]
